;[program:xxxx]
;environment=CONF_DIR=/etc/xxxx/yyy
;command=/opt/xxx/yyy
;autostart=true
;autorestart=true
;startsecs=2
;startretries=2
;stdout_logfile_maxbytes=10MB
;stdout_logfile_backups=10
;stderr_logfile=/var/log/xxx/error.log
;stdout_logfile=/var/log/xxx/access.log
;stderr_logfile_maxbytes=10MB
;stderr_logfile_backups=10